### ISSUE TITLE
Compressor does not play nice with {{ MEDIA_URL }}

### ISSUE THREAD

**Issue by mikl** [dziegler/django-css#2] opened 2009-08-06 08:17 UTC
I'm trying to deploy a site that worked fine with django-css in devel mode, even with compress switched on.

I have a compress stanza in my base.html that looks like this:

```
 {% compress css xhtml %}
<link rel="stylesheet" href="{{ MEDIA_URL }}css/reset.css" type="text/css" charset="utf-8" />
<link rel="stylesheet" href="{{ MEDIA_URL }}css/960.css" type="text/css" charset="utf-8" />
<link rel="stylesheet" href="{{ MEDIA_URL }}css/text.css" type="text/css" charset="utf-8" />
<link rel="stylesheet" href="{{ MEDIA_URL }}css/layout.ccss" type="text/css" charset="utf-8" />
{% block extra_css %}{% endblock %}
{% endcompress %}
```

When I open the site, I get a traceback in my server log, ending with:

> [Thu Aug 06 10:09:35 2009] [error] [client 90.184.195.240] UncompressableFileError: "css/reset.css" is not in COMPRESS_URL ("http://m.revealit.dk/revealit.dk/site_media/") and can not be compressed

It seems that django-css is somehow eating the output of `{{ MEDIA_URL }}`, because if I remove the {% compress %} tag, the URLs get rendered correctly (although the CleverCSS file obviously don't work without processing).

**Comment by mikl** [comment] 2009-08-06 08:23
There's a full traceback [here](http://dpaste.de/6waa/).

**Comment by dziegler** [comment] 2009-08-11 07:21
That's strange, `{{ MEDIA_URL }}` has always worked for me. Could you do me a favor and in templatetags/compress.py after line 68
    nodelist = parser.parse(('endcompress',))

could you add a print or log statement to print out `nodelist`, and then paste that here?

**Comment by mikl** [comment] 2009-08-11 09:06
[EDIT: I thought I had this figured out, but it turned out that it was partially due to that COMPRESS had been set as False while trying to debug.]

Here's the node lists:

```
[<Text Node: '
 <link rel="stylesheet"'>,
<Variable Node: MEDIA_URL>,
<Text Node: 'css/reset.css" type="text'>,
<Variable Node: MEDIA_URL>,
<Text Node: 'css/960.css" type="text/c'>,
<Variable Node: MEDIA_URL>,
<Text Node: 'css/text.css" type="text/'>,
<Variable Node: MEDIA_URL>,
<Text Node: 'css/layout.ccss" type="te'>,
<Block Node: extra_css. Contents: []>,
<Text Node: '
 '>]

[<Text Node: '
   <script type="text/j'>,
<Variable Node: MEDIA_URL>,
<Text Node: 'js/jquery.js"></script>
'>,
<Block Node: extra_js. Contents: []>,
<Text Node: '
   '>]
```

**Comment by mikl** [comment] 2009-08-11 10:34
Ah, I found another configuration error (wrong path to the yuicompressor jarfile) that was actually causing this. Somewhere, configuration error exceptions are caught and then this exception occurs later.

**Comment by dziegler** [comment] 2009-08-11 17:19
I tried messing up my clevercss and yuicompressor paths but still couldn't reproduce this. Since it looks like this was a config error, I'll close this issue, but I agree that it'd be nice if the reported errors pointed you toward the specific problem. Maybe I'll add something to check that the css compiler and compressor paths point to existing files.

**Closed as completed by dziegler** 2009-08-11 17:19 UTC
